mc_branch:
  - 'MCParticles.PDG'
  - 'MCParticles.generatorStatus'
  - 'MCParticles.simulatorStatus'
  - 'MCParticles.charge'
  - 'MCParticles.time'
  - 'MCParticles.mass'
  - 'MCParticles.vertex.x'
  - 'MCParticles.vertex.y'
  - 'MCParticles.vertex.z'
  - 'MCParticles.endpoint.x'
  - 'MCParticles.endpoint.y'
  - 'MCParticles.endpoint.z'
  - 'MCParticles.momentum.x'
  - 'MCParticles.momentum.y'
  - 'MCParticles.momentum.z'
  - 'MCParticles.momentumAtEndpoint.x'
  - 'MCParticles.momentumAtEndpoint.y'
  - 'MCParticles.momentumAtEndpoint.z'
  - 'MCParticles.spin.x'
  - 'MCParticles.spin.y'
  - 'MCParticles.spin.z'
  - 'MCParticles.colorFlow.a'
  - 'MCParticles.colorFlow.b'
  - 'MCParticles.parents_begin'
  - 'MCParticles.parents_end'
  - 'MCParticles.daughters_begin'
  - 'MCParticles.daughters_end'

track_feature_branch:
  - 'CentralTrackSegments.length'
  - 'CentralTrackSegments.lengthError'
  - 'CentralTrackSegments.points_begin'
  - 'CentralTrackSegments.points_end'
  - '_CentralTrackSegments_track.index'
  - '_CentralTrackSegments_track.collectionID'

track_branch:
  - '_CentralTrackSegments_points.surface'
  - '_CentralTrackSegments_points.system'
  - '_CentralTrackSegments_points.position.x'
  - '_CentralTrackSegments_points.position.y'
  - '_CentralTrackSegments_points.position.z'
  - '_CentralTrackSegments_points.positionError.xx'
  - '_CentralTrackSegments_points.positionError.yy'
  - '_CentralTrackSegments_points.positionError.zz'
  - '_CentralTrackSegments_points.positionError.xy'
  - '_CentralTrackSegments_points.positionError.xz'
  - '_CentralTrackSegments_points.positionError.yz'
  - '_CentralTrackSegments_points.momentum.x'
  - '_CentralTrackSegments_points.momentum.y'
  - '_CentralTrackSegments_points.momentum.z'
  - '_CentralTrackSegments_points.momentumError.xx'
  - '_CentralTrackSegments_points.momentumError.yy'
  - '_CentralTrackSegments_points.momentumError.zz'
  - '_CentralTrackSegments_points.momentumError.xy'
  - '_CentralTrackSegments_points.momentumError.xz'
  - '_CentralTrackSegments_points.momentumError.yz'
  - '_CentralTrackSegments_points.time'
  - '_CentralTrackSegments_points.timeError'
  - '_CentralTrackSegments_points.theta'
  - '_CentralTrackSegments_points.phi'
  - '_CentralTrackSegments_points.directionError.xx'
  - '_CentralTrackSegments_points.directionError.yy'
  - '_CentralTrackSegments_points.directionError.xy'
  - '_CentralTrackSegments_points.pathlength'
  - '_CentralTrackSegments_points.pathlengthError'
  - '_CentralTrackVertices_associatedParticles.index'
  - '_CentralTrackVertices_associatedParticles.collectionID'

btof_branch:
  - 'TOFBarrelRecHit.cellID'
  - 'TOFBarrelRecHit.position.x'
  - 'TOFBarrelRecHit.position.y'
  - 'TOFBarrelRecHit.position.z'
  - 'TOFBarrelRecHit.positionError.xx'
  - 'TOFBarrelRecHit.positionError.yy'
  - 'TOFBarrelRecHit.positionError.zz'
  - 'TOFBarrelRecHit.time'
  - 'TOFBarrelRecHit.timeError'
  - 'TOFBarrelRecHit.edep'
  - 'TOFBarrelRecHit.edepError'

etof_branch:
  - 'TOFEndcapRecHits.cellID'
  - 'TOFEndcapRecHits.position.x'
  - 'TOFEndcapRecHits.position.y'
  - 'TOFEndcapRecHits.position.z'
  - 'TOFEndcapRecHits.positionError.xx'
  - 'TOFEndcapRecHits.positionError.yy'
  - 'TOFEndcapRecHits.positionError.zz'
  - 'TOFEndcapRecHits.time'
  - 'TOFEndcapRecHits.timeError'
  - 'TOFEndcapRecHits.edep'
  - 'TOFEndcapRecHits.edepError'

btof_hit_associaction_branch:
  - '_TOFBarreHitAssociations_rawHit.index'
  - '_TOFBarreHitAssociations_rawHit.collectionID'

etof_hit_associaction_branch:
  - '_TOFEndcapHitAssociatedPoints.index'
  - '_TOFEndcapHitAssociatedPoints.collectionID'


original:
