directory_name: 'test2'
analysis_event_type: 'FILE_PATH_NCDIS_LARGE' 
# FILE_PATH_NCDIS_LARGE or FILE_PATH_SINGLE_PARTICLE_PION_OLDVERSION or FILE_PATH_SINGLE_PARTICLE_KAON_OLDVERSION or MYPYTHIA_FILE_PATH
matching_threshold_mc_track: 0.1
VERBOSE: True
PLOT_VERBOSE: True
DETAIL_PLOT_VERBOSE: False

SELECTED_EVENTS: 30000

#konosita mada mizissou
VERTEX_X_MIN: 20
VERTEX_X_MAX: 30
VERTEX_Y_MIN: 20
VERTEX_Y_MAX: 30
VERTEX_Z_MIN: 20
VERTEX_Z_MAX: 30